CREATE TABLE BOOK(
  BOOK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BOOK_NAME VARCHAR(50) NOT NULL,
  BOOK_AUTHOR VARCHAR(50) NOT NULL,
  BOOK_DESCRIPTION VARCHAR(500) NOT NULL
);

CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL
);